model_list:
  - model_name: o3-mini
    litellm_params:
      model: openai/o3-mini
      api_key: "os.environ/OPENAI_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: true

  - model_name: gpt-4.1
    litellm_params:
      model: openai/gpt-4.1
      api_key: "os.environ/OPENAI_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: true

  - model_name: gemini-2.5-pro-preview
    litellm_params:
      model: gemini/gemini-2.5-pro-preview-03-25
      api_key: "os.environ/GEMINI_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: true

  - model_name: gemini-2.0-flash
    litellm_params:
      model: gemini/gemini-2.0-flash
      api_key: "os.environ/GEMINI_API_KEY"
    model_info:
      free_tier_eligible: true
      is_private: true

  - model_name: gemini-2.0-flash-lite
    litellm_params:
      model: gemini/gemini-2.0-flash-lite
      api_key: "os.environ/GEMINI_API_KEY"
    model_info:
      free_tier_eligible: true
      is_private: true

  - model_name: claude-3-7-sonnet-latest
    litellm_params:
      model: anthropic/claude-3-7-sonnet-latest
      api_key: "os.environ/ANTHROPIC_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: true

  - model_name: deepseek-R1
    litellm_params:
      model: deepseek/deepseek-reasoner
      api_key: "os.environ/DEEPSEEK_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: false

  - model_name: deepseek-v3
    litellm_params:
      model: deepseek/deepseek-chat
      api_key: "os.environ/DEEPSEEK_API_KEY"
    model_info:
      free_tier_eligible: true
      is_private: false

  - model_name: grok-3-beta
    litellm_params:
      model: xai/grok-3-beta
      api_key: "os.environ/GROK_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: true

  - model_name: grok-3-fast-beta
    litellm_params:
      model: xai/grok-3-fast-beta
      api_key: "os.environ/GROK_API_KEY"
    model_info:
      free_tier_eligible: false
      is_private: true

  - model_name: grok-3-mini-beta
    litellm_params:
      model: xai/grok-3-mini-beta
      api_key: "os.environ/GROK_API_KEY"
    model_info:
      free_tier_eligible: true
      is_private: true
