use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Result;
use clap::Parser;
use clap::builder::RangedU64ValueParser;

mod agent;
mod agents_md;
mod bifrost_client;
mod codex_auth;
mod codex_client;
mod discovery;
mod llm_client;
mod multi_backend;
mod openrouter_auth;
mod sandbox_backend;
mod session;
mod skills;
mod tool_loop;
mod tools;

use crate::llm_client::LlmBackend;
use crate::multi_backend::{MultiBackend, OpenRouterAttribution};

/// Brokk ACP Server -- Rust-based Agent Client Protocol server with
/// zero-config auto-discovery: at startup we read `~/.codex/auth.json`
/// for Codex credentials and probe `http://localhost:11434/v1/models`
/// for Ollama, and the model picker shows whatever is reachable. No
/// flags are required (or even available) to point at a different
/// Ollama URL or restrict the picker -- if Ollama isn't on the default
/// port, it's simply not in the catalog.
#[derive(Parser)]
#[command(name = "brokk-acp", version, about)]
struct Args {
    /// Override the default model id for new sessions. Accepts a wire
    /// form (`codex::gpt-5-codex`, `ollama::llama3:latest`) or a bare id
    /// that routes to the preferred backend (Codex if available, else
    /// Ollama). When unset, the first discovered model wins.
    #[arg(long, default_value = "")]
    default_model: String,

    /// Maximum number of tool-calling turns per prompt before the server forces a final text response.
    #[arg(long, default_value_t = 25)]
    max_turns: usize,

    /// Maximum number of sessions to keep resident in memory before the
    /// least-recently-used session is evicted (the on-disk zip is unaffected
    /// and can be reloaded). Set to `0` to disable the cap.
    #[arg(long, default_value_t = 50)]
    max_sessions: usize,

    /// Maximum number of conversation turns retained per session in memory
    /// (sliding window). Older turns are dropped from memory once the cap is
    /// exceeded; the persisted zip retains the full history. Set to `0` to
    /// disable the cap.
    #[arg(long, default_value_t = 50)]
    max_history_turns: usize,

    /// Path to the bifrost binary (or just "bifrost" to look it up on $PATH).
    /// When unset, code-intelligence tools (search_symbols, etc.) are disabled.
    #[arg(long, env = "BROKK_BIFROST_BINARY")]
    bifrost_binary: Option<PathBuf>,

    /// Seconds of SSE inactivity before aborting a streaming LLM response.
    /// Counts only meaningful progress (parsed content/tool-call deltas);
    /// keepalive comments and unparseable chunks do not reset the timer.
    /// Bump higher for slow local models with large context (e.g. 600+ on a
    /// MacBook running a 70B). Overridable per-session via `/idle-timeout`.
    /// Bounds match the `/idle-timeout` slash command for a single,
    /// consistent UX between boot config and runtime override.
    #[arg(
        long,
        env = "BROKK_ACP_LLM_IDLE_TIMEOUT_SECS",
        default_value_t = llm_client::DEFAULT_IDLE_CHUNK_TIMEOUT_SECS,
        value_parser = RangedU64ValueParser::<u64>::new()
            .range(llm_client::MIN_IDLE_CHUNK_TIMEOUT_SECS..=llm_client::MAX_IDLE_CHUNK_TIMEOUT_SECS),
    )]
    llm_idle_timeout_secs: u64,

    // ----- Deprecated backward-compat flags --------------------------------
    // Existing editor configs generated by older brokk-code (Python TUI)
    // hand these in. We accept them silently so an upgrade-in-place
    // doesn't break the user's IDE -- but they no longer drive routing,
    // because Codex and Ollama auto-discover unconditionally. A warning
    // is logged at startup so users see they can clean these up next
    // time they re-run `brokk install`.
    /// DEPRECATED and ignored. Ollama is probed at the default URL
    /// `http://localhost:11434`; if your daemon listens elsewhere, run
    /// `ollama serve` on that port.
    #[arg(long, hide = true)]
    endpoint_url: Option<String>,

    /// DEPRECATED and ignored. Codex auto-detects credentials from
    /// `~/.codex/auth.json`; Ollama doesn't use an API key.
    #[arg(long, env = "BROKK_ENDPOINT_API_KEY", hide = true)]
    api_key: Option<String>,

    /// DEPRECATED and ignored. Codex is auto-detected when
    /// `~/.codex/auth.json` is present.
    #[arg(long, hide = true)]
    use_codex: bool,

    /// Disable the wasmtime-hosted parser sandbox and run all parsing
    /// (SKILL.md YAML, AGENTS.md, session zip, regex search) natively
    /// in-process. The sandbox guards against YAML bombs, ReDoS, and
    /// parser panics taking down the agent; disabling it trades that
    /// isolation for ~5-20ms per call and the host's full memory pool.
    #[arg(long, env = "BROKK_ACP_NO_WASM_SANDBOX", default_value_t = false)]
    no_wasm_sandbox: bool,
}

impl std::fmt::Debug for Args {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Args")
            .field("default_model", &self.default_model)
            .field("max_turns", &self.max_turns)
            .field("max_sessions", &self.max_sessions)
            .field("max_history_turns", &self.max_history_turns)
            .field("bifrost_binary", &self.bifrost_binary)
            .field("llm_idle_timeout_secs", &self.llm_idle_timeout_secs)
            // Deprecated flags omitted from Debug to avoid leaking api_key.
            .finish()
    }
}

/// Build a Codex backend from already-loaded credentials. Returns
/// `None` for the same "credentials are unusable" cases the startup
/// path treats as no-Codex (apikey mode without an API key, etc.) so
/// the picker stays honest.
///
/// Shared by the startup path (`build_codex_backend`) and the
/// post-`/codex-login` install path in `agent.rs`. Keeps the
/// `auth.auth_mode + tokens` decision tree in one place so the two
/// callers can't drift.
pub fn codex_backend_from_auth(auth: &codex_auth::AuthDotJson) -> Option<Arc<dyn LlmBackend>> {
    // ChatGPT-subscription routing requires both `auth_mode == "chatgpt"`
    // AND a usable `tokens` block. Anything else falls through to the
    // OPENAI_API_KEY path -- including `chatgpt` mode with no tokens
    // (which can happen if a refresh just blew them away), `apikey` mode
    // (the documented API-billed fallback), and any unrecognized mode
    // string from a future codex-cli version. If we hit the apikey path
    // with no key, the prompt would 401 -- skip in that case so the
    // picker is honest about what's available.
    if matches!(auth.auth_mode.as_deref(), Some("chatgpt")) && auth.tokens.is_some() {
        return Some(Arc::new(codex_client::CodexClient::new()));
    }
    let key = auth.openai_api_key.clone();
    key.map(|k| {
        Arc::new(llm_client::OpenAiClient::new(
            "https://api.openai.com/v1".to_string(),
            Some(k),
        )) as Arc<dyn LlmBackend>
    })
}

/// Build the Codex backend if `~/.codex/auth.json` is present. Returns
/// `None` when the file is missing or unreadable. Stale credentials
/// are refreshed proactively so the first prompt doesn't burn a 401
/// round-trip.
async fn build_codex_backend() -> Option<Arc<dyn LlmBackend>> {
    let mut auth = match codex_auth::read_auth_dot_json() {
        Ok(Some(a)) => a,
        Ok(None) => {
            tracing::info!(
                "no ~/.codex/auth.json found; Codex auto-discovery skipped. Run /codex-login from a session to authenticate."
            );
            return None;
        }
        Err(e) => {
            tracing::warn!("failed to read ~/.codex/auth.json: {e:#}");
            return None;
        }
    };
    if let Err(e) = codex_auth::refresh_if_stale(&mut auth).await {
        tracing::warn!("codex credential refresh failed: {e:#}");
    }
    let backend = codex_backend_from_auth(&auth);
    match (&backend, auth.auth_mode.as_deref(), auth.tokens.is_some()) {
        (Some(_), Some("chatgpt"), true) => {
            tracing::info!(
                "Codex backend enabled in ChatGPT subscription mode (Responses API on chatgpt.com)"
            );
        }
        (Some(_), mode, _) => {
            tracing::info!(
                "Codex backend enabled in OPENAI_API_KEY mode (api.openai.com), auth_mode={:?}",
                mode
            );
        }
        (None, mode, _) => {
            tracing::warn!(
                "~/.codex/auth.json is unusable (auth_mode={:?}, no OPENAI_API_KEY); \
                 skipping Codex backend. Run /codex-login to re-authenticate.",
                mode
            );
        }
    }
    backend
}

/// Build the Ollama chat backend pointed at `base_url`. Chat requests go
/// through Ollama's OpenAI-compatible `/v1/chat/completions` shim, while
/// discovery (handled by `discovery.rs`) hits the OpenAI-compatible
/// `/v1/models`. Ollama doesn't require an API key for local use.
///
/// Shared by the startup path (which always passes
/// `discovery::OLLAMA_DEFAULT_URL`) and `/configure ollama.endpoint`,
/// which swaps the URL at runtime and reinstalls the backend.
pub fn build_ollama_backend(base_url: &str) -> Arc<dyn LlmBackend> {
    let chat_url = format!("{base_url}/v1");
    tracing::info!(
        "Ollama backend wired at {chat_url} (chat) and {base_url}/v1/models (discovery); \
         models become available if/when the daemon responds"
    );
    Arc::new(llm_client::OpenAiClient::new(chat_url, None))
}

/// Build an OpenRouter chat backend from a raw API key. OpenRouter speaks
/// the OpenAI Chat Completions wire format verbatim, so we reuse
/// `OpenAiClient` with the OpenRouter base URL and attach the
/// `HTTP-Referer` / `X-Title` attribution headers (these drive the
/// openrouter.ai leaderboard rankings; both are documented as optional
/// but we always set them so the app shows up consistently).
///
/// The attribution values come from the caller so `/configure
/// openrouter.http_referer` and `/configure openrouter.x_title` can
/// override the defaults at runtime: header values are baked into the
/// `reqwest::Client` defaults at construction, so a change requires
/// rebuilding the backend.
///
/// Whitespace is trimmed so accidental shell quoting
/// (`export OPENROUTER_API_KEY=" sk-..."`) doesn't 401 every request.
/// Returns `None` for an empty key, or for an attribution value that
/// can't be encoded as an HTTP header (so a `/configure` typo doesn't
/// take the backend down silently).
pub fn openrouter_backend_from_key(
    raw: &str,
    attribution: &OpenRouterAttribution,
) -> Option<Arc<dyn LlmBackend>> {
    let key = raw.trim();
    if key.is_empty() {
        return None;
    }

    let mut headers = reqwest::header::HeaderMap::new();
    // Header names are well-known ASCII -- `from_static` for the names
    // is fine. Values come from `OpenRouterAttribution`, which is
    // mutable at runtime via `/configure`, so build them with
    // `from_str` and surface a `None` (skip install) on an invalid
    // value rather than panicking.
    let referer_value = match reqwest::header::HeaderValue::from_str(&attribution.http_referer) {
        Ok(v) => v,
        Err(e) => {
            tracing::warn!(
                "OpenRouter http_referer is not a valid header value ({e}); skipping backend build"
            );
            return None;
        }
    };
    let title_value = match reqwest::header::HeaderValue::from_str(&attribution.x_title) {
        Ok(v) => v,
        Err(e) => {
            tracing::warn!(
                "OpenRouter x_title is not a valid header value ({e}); skipping backend build"
            );
            return None;
        }
    };
    headers.insert(
        reqwest::header::HeaderName::from_static("http-referer"),
        referer_value,
    );
    headers.insert(
        reqwest::header::HeaderName::from_static("x-title"),
        title_value,
    );

    Some(Arc::new(llm_client::OpenAiClient::with_default_headers(
        discovery::OPENROUTER_BASE_URL.to_string(),
        Some(key.to_string()),
        headers,
    )))
}

/// Build the OpenRouter chat backend from the first available credential
/// source. Auth posture mirrors Codex: zero-config -- if neither the env
/// var nor the on-disk file holds a usable key the backend is skipped
/// silently, no CLI flag required.
///
/// Precedence is env > file: an explicit `OPENROUTER_API_KEY=...` in the
/// shell that launched the server overrides a stale on-disk key, so a
/// user rotating their key in a shell session doesn't have to remember
/// to `/openrouter-login` first. The on-disk file (written by
/// `/openrouter-login <key>` mid-session) is the persistent fallback for
/// the common case of starting the server without env vars.
fn build_openrouter_backend(attribution: &OpenRouterAttribution) -> Option<Arc<dyn LlmBackend>> {
    // Delegate the env > file precedence to the canonical resolver so
    // `/configure openrouter.http_referer` (which reads the same key to
    // rebuild the backend on attribution change) can never drift from
    // the startup probe. The resolver returns None when both env and
    // on-disk file are empty or unreadable.
    let key = agent::current_openrouter_key()?;
    // Re-probe the env var just for logging so the line tells the
    // operator where the key came from. The resolver already trimmed
    // and validated it.
    let env_present = std::env::var(discovery::OPENROUTER_API_KEY_ENV)
        .ok()
        .map(|raw| !raw.trim().is_empty())
        .unwrap_or(false);
    if env_present {
        tracing::info!(
            "OpenRouter backend wired from {} at {} (chat + discovery); key length={}",
            discovery::OPENROUTER_API_KEY_ENV,
            discovery::OPENROUTER_BASE_URL,
            key.len()
        );
    } else {
        tracing::info!(
            "OpenRouter backend wired from on-disk credentials at {} (chat + discovery); key length={}",
            discovery::OPENROUTER_BASE_URL,
            key.len()
        );
    }
    openrouter_backend_from_key(&key, attribution)
}

#[tokio::main]
async fn main() -> Result<()> {
    // Configure tracing to stderr only (stdout is reserved for JSON-RPC)
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let args = Args::parse();

    // Install the parser sandbox before any code that might load a SKILL.md
    // (or, eventually, parse AGENTS.md / session zips / regex queries) so
    // every parse goes through the chosen backend from the first call.
    // The wasm backend is the default; `--no-wasm-sandbox` is the explicit
    // opt-out that trades isolation for raw speed.
    if args.no_wasm_sandbox {
        tracing::info!(
            "wasm parser sandbox disabled by flag; YAML/zip/regex parses run natively in-process"
        );
        sandbox_backend::install_global(sandbox_backend::SandboxBackend::Native);
    } else {
        sandbox_backend::install_global(sandbox_backend::SandboxBackend::wasm_or_native());
    }

    if args.endpoint_url.is_some() {
        tracing::warn!(
            "--endpoint-url is deprecated and ignored. Ollama is probed at \
             http://localhost:11434; if your daemon listens elsewhere, run it on the \
             default port. Re-run `brokk install` to refresh your editor config."
        );
    }
    if args.api_key.is_some() {
        tracing::warn!(
            "--api-key (env BROKK_ENDPOINT_API_KEY) is deprecated and ignored. \
             Codex credentials are read from ~/.codex/auth.json; Ollama does not use a key."
        );
    }
    if args.use_codex {
        tracing::warn!(
            "--use-codex is deprecated and has no effect. Codex is auto-detected when \
             ~/.codex/auth.json exists, alongside Ollama."
        );
    }

    // Build the OpenRouter backend with the same default attribution
    // `MultiBackend` will hold in its cell, so `/configure
    // openrouter.http_referer` / `x_title` rebuilds the client against
    // the same baseline the startup probe used.
    let codex_backend = build_codex_backend().await;
    let openrouter_backend = build_openrouter_backend(&OpenRouterAttribution::default());
    let ollama_backend = Some(build_ollama_backend(discovery::OLLAMA_DEFAULT_URL));

    if codex_backend.is_none() {
        tracing::info!(
            "Codex backend not available; the picker will fall back to OpenRouter \
             and Ollama (if discovered). Run /codex-login from a session to add \
             Codex -- the new credentials are picked up on the next discovery \
             refresh, no restart required."
        );
    }
    if openrouter_backend.is_none() {
        tracing::info!(
            "OpenRouter backend not available; set {} or run `/openrouter-login <key>` \
             from a session to enable it.",
            discovery::OPENROUTER_API_KEY_ENV
        );
    }

    let llm: Arc<MultiBackend> = Arc::new(MultiBackend::new(
        codex_backend,
        openrouter_backend,
        ollama_backend,
    ));

    let limits = session::SessionLimits {
        max_sessions: args.max_sessions,
        max_history_turns: args.max_history_turns,
    };
    let sessions = session::SessionStore::with_limits(args.default_model, limits);

    let max_turns = args.max_turns.max(1);
    // Bounds on `llm_idle_timeout_secs` are enforced by the clap
    // `value_parser`, so the value reaches us already validated.
    agent::run_agent(
        llm,
        sessions,
        max_turns,
        args.llm_idle_timeout_secs,
        args.bifrost_binary,
    )
    .await
    .map_err(|e| {
        tracing::error!("agent error: {e}");
        anyhow::anyhow!("agent error: {e}")
    })
}
