use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Result;
use clap::Parser;
use clap::builder::RangedU64ValueParser;

mod agent;
mod agents_md;
mod bifrost_client;
mod codex_auth;
mod codex_client;
mod discovery;
mod llm_client;
mod multi_backend;
mod openrouter_auth;
mod sandbox_backend;
mod session;
mod skills;
mod tool_loop;
mod tools;

use crate::llm_client::LlmBackend;
use crate::multi_backend::MultiBackend;

/// Brokk ACP Server -- Rust-based Agent Client Protocol server with
/// zero-config auto-discovery: at startup we read `~/.codex/auth.json`
/// for Codex credentials and probe `http://localhost:11434/api/tags`
/// for Ollama, and the model picker shows whatever is reachable. No
/// flags are required (or even available) to point at a different
/// Ollama URL or restrict the picker -- if Ollama isn't on the default
/// port, it's simply not in the catalog.
#[derive(Parser)]
#[command(name = "brokk-acp", version, about)]
struct Args {
    /// Override the default model id for new sessions. Accepts a wire
    /// form (`codex::gpt-5-codex`, `ollama::llama3:latest`) or a bare id
    /// that routes to the preferred backend (Codex if available, else
    /// Ollama). When unset, the first discovered model wins.
    #[arg(long, default_value = "")]
    default_model: String,

    /// Maximum number of tool-calling turns per prompt before the server forces a final text response.
    #[arg(long, default_value_t = 25)]
    max_turns: usize,

    /// Maximum number of sessions to keep resident in memory before the
    /// least-recently-used session is evicted (the on-disk zip is unaffected
    /// and can be reloaded). Set to `0` to disable the cap.
    #[arg(long, default_value_t = 50)]
    max_sessions: usize,

    /// Maximum number of conversation turns retained per session in memory
    /// (sliding window). Older turns are dropped from memory once the cap is
    /// exceeded; the persisted zip retains the full history. Set to `0` to
    /// disable the cap.
    #[arg(long, default_value_t = 50)]
    max_history_turns: usize,

    /// Path to the bifrost binary (or just "bifrost" to look it up on $PATH).
    /// When unset, code-intelligence tools (search_symbols, etc.) are disabled.
    #[arg(long, env = "BROKK_BIFROST_BINARY")]
    bifrost_binary: Option<PathBuf>,

    /// Seconds of SSE inactivity before aborting a streaming LLM response.
    /// Counts only meaningful progress (parsed content/tool-call deltas);
    /// keepalive comments and unparseable chunks do not reset the timer.
    /// Bump higher for slow local models with large context (e.g. 600+ on a
    /// MacBook running a 70B). Overridable per-session via `/idle-timeout`.
    /// Bounds match the `/idle-timeout` slash command for a single,
    /// consistent UX between boot config and runtime override.
    #[arg(
        long,
        env = "BROKK_ACP_LLM_IDLE_TIMEOUT_SECS",
        default_value_t = llm_client::DEFAULT_IDLE_CHUNK_TIMEOUT_SECS,
        value_parser = RangedU64ValueParser::<u64>::new()
            .range(llm_client::MIN_IDLE_CHUNK_TIMEOUT_SECS..=llm_client::MAX_IDLE_CHUNK_TIMEOUT_SECS),
    )]
    llm_idle_timeout_secs: u64,

    // ----- Deprecated backward-compat flags --------------------------------
    // Existing editor configs generated by older brokk-code (Python TUI)
    // hand these in. We accept them silently so an upgrade-in-place
    // doesn't break the user's IDE -- but they no longer drive routing,
    // because Codex and Ollama auto-discover unconditionally. A warning
    // is logged at startup so users see they can clean these up next
    // time they re-run `brokk install`.
    /// DEPRECATED and ignored. Ollama is probed at the default URL
    /// `http://localhost:11434`; if your daemon listens elsewhere, run
    /// `ollama serve` on that port.
    #[arg(long, hide = true)]
    endpoint_url: Option<String>,

    /// DEPRECATED and ignored. Codex auto-detects credentials from
    /// `~/.codex/auth.json`; Ollama doesn't use an API key.
    #[arg(long, env = "BROKK_ENDPOINT_API_KEY", hide = true)]
    api_key: Option<String>,

    /// DEPRECATED and ignored. Codex is auto-detected when
    /// `~/.codex/auth.json` is present.
    #[arg(long, hide = true)]
    use_codex: bool,

    /// Disable the wasmtime-hosted parser sandbox and run all parsing
    /// (SKILL.md YAML, AGENTS.md, session zip, regex search) natively
    /// in-process. The sandbox guards against YAML bombs, ReDoS, and
    /// parser panics taking down the agent; disabling it trades that
    /// isolation for ~5-20ms per call and the host's full memory pool.
    #[arg(long, env = "BROKK_ACP_NO_WASM_SANDBOX", default_value_t = false)]
    no_wasm_sandbox: bool,
}

impl std::fmt::Debug for Args {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Args")
            .field("default_model", &self.default_model)
            .field("max_turns", &self.max_turns)
            .field("max_sessions", &self.max_sessions)
            .field("max_history_turns", &self.max_history_turns)
            .field("bifrost_binary", &self.bifrost_binary)
            .field("llm_idle_timeout_secs", &self.llm_idle_timeout_secs)
            // Deprecated flags omitted from Debug to avoid leaking api_key.
            .finish()
    }
}

/// Build a Codex backend from already-loaded credentials. Returns
/// `None` for the same "credentials are unusable" cases the startup
/// path treats as no-Codex (apikey mode without an API key, etc.) so
/// the picker stays honest.
///
/// Shared by the startup path (`build_codex_backend`) and the
/// post-`/codex-login` install path in `agent.rs`. Keeps the
/// `auth.auth_mode + tokens` decision tree in one place so the two
/// callers can't drift.
pub fn codex_backend_from_auth(auth: &codex_auth::AuthDotJson) -> Option<Arc<dyn LlmBackend>> {
    // ChatGPT-subscription routing requires both `auth_mode == "chatgpt"`
    // AND a usable `tokens` block. Anything else falls through to the
    // OPENAI_API_KEY path -- including `chatgpt` mode with no tokens
    // (which can happen if a refresh just blew them away), `apikey` mode
    // (the documented API-billed fallback), and any unrecognized mode
    // string from a future codex-cli version. If we hit the apikey path
    // with no key, the prompt would 401 -- skip in that case so the
    // picker is honest about what's available.
    if matches!(auth.auth_mode.as_deref(), Some("chatgpt")) && auth.tokens.is_some() {
        return Some(Arc::new(codex_client::CodexClient::new()));
    }
    let key = auth.openai_api_key.clone();
    key.map(|k| {
        Arc::new(llm_client::OpenAiClient::new(
            "https://api.openai.com/v1".to_string(),
            Some(k),
        )) as Arc<dyn LlmBackend>
    })
}

/// Build the Codex backend if `~/.codex/auth.json` is present. Returns
/// `None` when the file is missing or unreadable. Stale credentials
/// are refreshed proactively so the first prompt doesn't burn a 401
/// round-trip.
async fn build_codex_backend() -> Option<Arc<dyn LlmBackend>> {
    let mut auth = match codex_auth::read_auth_dot_json() {
        Ok(Some(a)) => a,
        Ok(None) => {
            tracing::info!(
                "no ~/.codex/auth.json found; Codex auto-discovery skipped. Run /codex-login from a session to authenticate."
            );
            return None;
        }
        Err(e) => {
            tracing::warn!("failed to read ~/.codex/auth.json: {e:#}");
            return None;
        }
    };
    if let Err(e) = codex_auth::refresh_if_stale(&mut auth).await {
        tracing::warn!("codex credential refresh failed: {e:#}");
    }
    let backend = codex_backend_from_auth(&auth);
    match (&backend, auth.auth_mode.as_deref(), auth.tokens.is_some()) {
        (Some(_), Some("chatgpt"), true) => {
            tracing::info!(
                "Codex backend enabled in ChatGPT subscription mode (Responses API on chatgpt.com)"
            );
        }
        (Some(_), mode, _) => {
            tracing::info!(
                "Codex backend enabled in OPENAI_API_KEY mode (api.openai.com), auth_mode={:?}",
                mode
            );
        }
        (None, mode, _) => {
            tracing::warn!(
                "~/.codex/auth.json is unusable (auth_mode={:?}, no OPENAI_API_KEY); \
                 skipping Codex backend. Run /codex-login to re-authenticate.",
                mode
            );
        }
    }
    backend
}

/// Build the Ollama chat backend. Always pointed at the default
/// `http://localhost:11434`; chat requests go through Ollama's
/// OpenAI-compatible `/v1/chat/completions` shim, while discovery
/// (handled by `discovery.rs`) hits the native `/api/tags`. Ollama
/// doesn't require an API key for local use.
fn build_ollama_backend() -> Arc<dyn LlmBackend> {
    let chat_url = format!("{}/v1", discovery::OLLAMA_DEFAULT_URL);
    tracing::info!(
        "Ollama backend wired at {chat_url} (chat) and {}/api/tags (discovery); \
         models become available if/when the daemon responds",
        discovery::OLLAMA_DEFAULT_URL
    );
    Arc::new(llm_client::OpenAiClient::new(chat_url, None))
}

/// Build an OpenRouter chat backend from a raw API key. OpenRouter speaks
/// the OpenAI Chat Completions wire format verbatim, so we reuse
/// `OpenAiClient` with the OpenRouter base URL and attach the optional
/// `HTTP-Referer` / `X-Title` attribution headers (these drive the
/// openrouter.ai leaderboard rankings; both are documented as optional
/// but we always set them so the app shows up consistently).
///
/// Whitespace is trimmed so accidental shell quoting
/// (`export OPENROUTER_API_KEY=" sk-..."`) doesn't 401 every request.
/// Returns `None` for an empty key so callers can distinguish "not
/// configured" from "configured but broken".
pub fn openrouter_backend_from_key(raw: &str) -> Option<Arc<dyn LlmBackend>> {
    let key = raw.trim();
    if key.is_empty() {
        return None;
    }

    let mut headers = reqwest::header::HeaderMap::new();
    // Both header values are well-known ASCII strings the API expects;
    // `from_static` panics only on invalid header bytes, which these
    // literals are not. Doing this once at startup means we don't pay
    // header-construction overhead per request.
    headers.insert(
        reqwest::header::HeaderName::from_static("http-referer"),
        reqwest::header::HeaderValue::from_static("https://github.com/BrokkAi/brokk"),
    );
    headers.insert(
        reqwest::header::HeaderName::from_static("x-title"),
        reqwest::header::HeaderValue::from_static("brokk-acp-rust"),
    );

    Some(Arc::new(llm_client::OpenAiClient::with_default_headers(
        discovery::OPENROUTER_BASE_URL.to_string(),
        Some(key.to_string()),
        headers,
    )))
}

/// Build the OpenRouter chat backend from the first available credential
/// source. Auth posture mirrors Codex: zero-config -- if neither the env
/// var nor the on-disk file holds a usable key the backend is skipped
/// silently, no CLI flag required.
///
/// Precedence is env > file: an explicit `OPENROUTER_API_KEY=...` in the
/// shell that launched the server overrides a stale on-disk key, so a
/// user rotating their key in a shell session doesn't have to remember
/// to `/openrouter-login` first. The on-disk file (written by
/// `/openrouter-login <key>` mid-session) is the persistent fallback for
/// the common case of starting the server without env vars.
fn build_openrouter_backend() -> Option<Arc<dyn LlmBackend>> {
    if let Ok(raw) = std::env::var(discovery::OPENROUTER_API_KEY_ENV) {
        let trimmed = raw.trim();
        if trimmed.is_empty() {
            tracing::info!(
                "{} is set but empty; falling back to {}",
                discovery::OPENROUTER_API_KEY_ENV,
                openrouter_auth::auth_path()
                    .map(|p| p.display().to_string())
                    .unwrap_or_else(|_| "on-disk credential file".to_string())
            );
        } else {
            tracing::info!(
                "OpenRouter backend wired from {} at {} (chat + discovery); key length={}",
                discovery::OPENROUTER_API_KEY_ENV,
                discovery::OPENROUTER_BASE_URL,
                trimmed.len()
            );
            return openrouter_backend_from_key(trimmed);
        }
    }

    match openrouter_auth::read() {
        Ok(Some(auth)) => {
            let trimmed = auth.api_key.trim();
            if trimmed.is_empty() {
                tracing::info!(
                    "OpenRouter credential file exists but contains an empty key; backend skipped"
                );
                return None;
            }
            tracing::info!(
                "OpenRouter backend wired from on-disk credentials at {} (chat + discovery); key length={}",
                discovery::OPENROUTER_BASE_URL,
                trimmed.len()
            );
            openrouter_backend_from_key(trimmed)
        }
        Ok(None) => None,
        Err(e) => {
            tracing::warn!("failed to read OpenRouter credential file: {e:#}");
            None
        }
    }
}

#[tokio::main]
async fn main() -> Result<()> {
    // Configure tracing to stderr only (stdout is reserved for JSON-RPC)
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let args = Args::parse();

    // Install the parser sandbox before any code that might load a SKILL.md
    // (or, eventually, parse AGENTS.md / session zips / regex queries) so
    // every parse goes through the chosen backend from the first call.
    // The wasm backend is the default; `--no-wasm-sandbox` is the explicit
    // opt-out that trades isolation for raw speed.
    if args.no_wasm_sandbox {
        tracing::info!(
            "wasm parser sandbox disabled by flag; YAML/zip/regex parses run natively in-process"
        );
        sandbox_backend::install_global(sandbox_backend::SandboxBackend::Native);
    } else {
        sandbox_backend::install_global(sandbox_backend::SandboxBackend::wasm_or_native());
    }

    if args.endpoint_url.is_some() {
        tracing::warn!(
            "--endpoint-url is deprecated and ignored. Ollama is probed at \
             http://localhost:11434; if your daemon listens elsewhere, run it on the \
             default port. Re-run `brokk install` to refresh your editor config."
        );
    }
    if args.api_key.is_some() {
        tracing::warn!(
            "--api-key (env BROKK_ENDPOINT_API_KEY) is deprecated and ignored. \
             Codex credentials are read from ~/.codex/auth.json; Ollama does not use a key."
        );
    }
    if args.use_codex {
        tracing::warn!(
            "--use-codex is deprecated and has no effect. Codex is auto-detected when \
             ~/.codex/auth.json exists, alongside Ollama."
        );
    }

    let codex_backend = build_codex_backend().await;
    let openrouter_backend = build_openrouter_backend();
    let ollama_backend = Some(build_ollama_backend());

    if codex_backend.is_none() {
        tracing::info!(
            "Codex backend not available; the picker will fall back to OpenRouter \
             and Ollama (if discovered). Run /codex-login from a session to add \
             Codex -- the new credentials are picked up on the next discovery \
             refresh, no restart required."
        );
    }
    if openrouter_backend.is_none() {
        tracing::info!(
            "OpenRouter backend not available; set {} or run `/openrouter-login <key>` \
             from a session to enable it.",
            discovery::OPENROUTER_API_KEY_ENV
        );
    }

    let llm: Arc<MultiBackend> = Arc::new(MultiBackend::new(
        codex_backend,
        openrouter_backend,
        ollama_backend,
    ));

    let limits = session::SessionLimits {
        max_sessions: args.max_sessions,
        max_history_turns: args.max_history_turns,
    };
    let sessions = session::SessionStore::with_limits(args.default_model, limits);

    let max_turns = args.max_turns.max(1);
    // Bounds on `llm_idle_timeout_secs` are enforced by the clap
    // `value_parser`, so the value reaches us already validated.
    agent::run_agent(
        llm,
        sessions,
        max_turns,
        args.llm_idle_timeout_secs,
        args.bifrost_binary,
    )
    .await
    .map_err(|e| {
        tracing::error!("agent error: {e}");
        anyhow::anyhow!("agent error: {e}")
    })
}
