use std::path::PathBuf;
use std::sync::Arc;

use anyhow::Result;
use clap::Parser;

mod agent;
mod bifrost_client;
mod codex_auth;
mod codex_client;
mod discovery;
mod llm_client;
mod multi_backend;
mod session;
mod tool_loop;
mod tools;

use crate::llm_client::LlmBackend;
use crate::multi_backend::MultiBackend;

/// Brokk ACP Server -- Rust-based Agent Client Protocol server with
/// zero-config auto-discovery: at startup we read `~/.codex/auth.json`
/// for Codex credentials and probe `http://localhost:11434/api/tags`
/// for Ollama, and the model picker shows whatever is reachable. No
/// flags are required (or even available) to point at a different
/// Ollama URL or restrict the picker -- if Ollama isn't on the default
/// port, it's simply not in the catalog.
#[derive(Parser)]
#[command(name = "brokk-acp", version, about)]
struct Args {
    /// Override the default model id for new sessions. Accepts a wire
    /// form (`codex::gpt-5-codex`, `ollama::llama3:latest`) or a bare id
    /// that routes to the preferred backend (Codex if available, else
    /// Ollama). When unset, the first discovered model wins.
    #[arg(long, default_value = "")]
    default_model: String,

    /// Maximum number of tool-calling turns per prompt before the server forces a final text response.
    #[arg(long, default_value_t = 25)]
    max_turns: usize,

    /// Maximum number of sessions to keep resident in memory before the
    /// least-recently-used session is evicted (the on-disk zip is unaffected
    /// and can be reloaded). Set to `0` to disable the cap.
    #[arg(long, default_value_t = 50)]
    max_sessions: usize,

    /// Maximum number of conversation turns retained per session in memory
    /// (sliding window). Older turns are dropped from memory once the cap is
    /// exceeded; the persisted zip retains the full history. Set to `0` to
    /// disable the cap.
    #[arg(long, default_value_t = 50)]
    max_history_turns: usize,

    /// Path to the bifrost binary (or just "bifrost" to look it up on $PATH).
    /// When unset, code-intelligence tools (search_symbols, etc.) are disabled.
    #[arg(long, env = "BROKK_BIFROST_BINARY")]
    bifrost_binary: Option<PathBuf>,

    // ----- Deprecated backward-compat flags --------------------------------
    // Existing editor configs generated by older brokk-code (Python TUI)
    // hand these in. We accept them silently so an upgrade-in-place
    // doesn't break the user's IDE -- but they no longer drive routing,
    // because Codex and Ollama auto-discover unconditionally. A warning
    // is logged at startup so users see they can clean these up next
    // time they re-run `brokk install`.
    /// DEPRECATED and ignored. Ollama is probed at the default URL
    /// `http://localhost:11434`; if your daemon listens elsewhere, run
    /// `ollama serve` on that port.
    #[arg(long, hide = true)]
    endpoint_url: Option<String>,

    /// DEPRECATED and ignored. Codex auto-detects credentials from
    /// `~/.codex/auth.json`; Ollama doesn't use an API key.
    #[arg(long, env = "BROKK_ENDPOINT_API_KEY", hide = true)]
    api_key: Option<String>,

    /// DEPRECATED and ignored. Codex is auto-detected when
    /// `~/.codex/auth.json` is present.
    #[arg(long, hide = true)]
    use_codex: bool,
}

impl std::fmt::Debug for Args {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Args")
            .field("default_model", &self.default_model)
            .field("max_turns", &self.max_turns)
            .field("max_sessions", &self.max_sessions)
            .field("max_history_turns", &self.max_history_turns)
            .field("bifrost_binary", &self.bifrost_binary)
            // Deprecated flags omitted from Debug to avoid leaking api_key.
            .finish()
    }
}

/// Build the Codex backend if `~/.codex/auth.json` is present. Returns
/// `None` when the file is missing or unreadable. Stale credentials
/// are refreshed proactively so the first prompt doesn't burn a 401
/// round-trip.
async fn build_codex_backend() -> Option<Arc<dyn LlmBackend>> {
    let mut auth = match codex_auth::read_auth_dot_json() {
        Ok(Some(a)) => a,
        Ok(None) => {
            tracing::info!(
                "no ~/.codex/auth.json found; Codex auto-discovery skipped. Run /codex-login from a session to authenticate."
            );
            return None;
        }
        Err(e) => {
            tracing::warn!("failed to read ~/.codex/auth.json: {e:#}");
            return None;
        }
    };
    if let Err(e) = codex_auth::refresh_if_stale(&mut auth).await {
        tracing::warn!("codex credential refresh failed: {e:#}");
    }
    // ChatGPT-subscription routing requires both `auth_mode == "chatgpt"`
    // AND a usable `tokens` block. Anything else falls through to the
    // OPENAI_API_KEY path -- including `chatgpt` mode with no tokens
    // (which can happen if a refresh just blew them away), `apikey` mode
    // (the documented API-billed fallback), and any unrecognized mode
    // string from a future codex-cli version. If we hit the apikey path
    // with no key, the prompt would 401 -- skip in that case so the
    // picker is honest about what's available.
    if matches!(auth.auth_mode.as_deref(), Some("chatgpt")) && auth.tokens.is_some() {
        tracing::info!(
            "Codex backend enabled in ChatGPT subscription mode (Responses API on chatgpt.com)"
        );
        return Some(Arc::new(codex_client::CodexClient::new()));
    }
    let key = auth.openai_api_key.clone();
    if key.is_none() {
        tracing::warn!(
            "~/.codex/auth.json is unusable (auth_mode={:?}, no OPENAI_API_KEY); \
             skipping Codex backend. Run /codex-login to re-authenticate.",
            auth.auth_mode
        );
        return None;
    }
    tracing::info!(
        "Codex backend enabled in OPENAI_API_KEY mode (api.openai.com), auth_mode={:?}",
        auth.auth_mode
    );
    Some(Arc::new(llm_client::OpenAiClient::new(
        "https://api.openai.com/v1".to_string(),
        key,
    )))
}

/// Build the Ollama chat backend. Always pointed at the default
/// `http://localhost:11434`; chat requests go through Ollama's
/// OpenAI-compatible `/v1/chat/completions` shim, while discovery
/// (handled by `discovery.rs`) hits the native `/api/tags`. Ollama
/// doesn't require an API key for local use.
fn build_ollama_backend() -> Arc<dyn LlmBackend> {
    let chat_url = format!("{}/v1", discovery::OLLAMA_DEFAULT_URL);
    tracing::info!(
        "Ollama backend wired at {chat_url} (chat) and {}/api/tags (discovery); \
         models become available if/when the daemon responds",
        discovery::OLLAMA_DEFAULT_URL
    );
    Arc::new(llm_client::OpenAiClient::new(chat_url, None))
}

#[tokio::main]
async fn main() -> Result<()> {
    // Configure tracing to stderr only (stdout is reserved for JSON-RPC)
    tracing_subscriber::fmt()
        .with_writer(std::io::stderr)
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .init();

    let args = Args::parse();

    if args.endpoint_url.is_some() {
        tracing::warn!(
            "--endpoint-url is deprecated and ignored. Ollama is probed at \
             http://localhost:11434; if your daemon listens elsewhere, run it on the \
             default port. Re-run `brokk install` to refresh your editor config."
        );
    }
    if args.api_key.is_some() {
        tracing::warn!(
            "--api-key (env BROKK_ENDPOINT_API_KEY) is deprecated and ignored. \
             Codex credentials are read from ~/.codex/auth.json; Ollama does not use a key."
        );
    }
    if args.use_codex {
        tracing::warn!(
            "--use-codex is deprecated and has no effect. Codex is auto-detected when \
             ~/.codex/auth.json exists, alongside Ollama."
        );
    }

    let codex_backend = build_codex_backend().await;
    let ollama_backend = Some(build_ollama_backend());

    if codex_backend.is_none() {
        tracing::info!(
            "Codex backend not available; the picker will only show Ollama models. \
             Run /codex-login from a session to add Codex (a server restart picks up the new auth)."
        );
    }

    let llm: Arc<dyn LlmBackend> = Arc::new(MultiBackend::new(codex_backend, ollama_backend));

    let limits = session::SessionLimits {
        max_sessions: args.max_sessions,
        max_history_turns: args.max_history_turns,
    };
    let sessions = session::SessionStore::with_limits(args.default_model, limits);

    let max_turns = args.max_turns.max(1);
    agent::run_agent(llm, sessions, max_turns, args.bifrost_binary)
        .await
        .map_err(|e| {
            tracing::error!("agent error: {e}");
            anyhow::anyhow!("agent error: {e}")
        })
}
