package ai.brokk.tools;

import ai.brokk.analyzer.CodeUnit;
import ai.brokk.analyzer.CodeUnitType;
import ai.brokk.analyzer.JavaAnalyzer;
import ai.brokk.analyzer.ProjectFile;
import ai.brokk.project.IProject;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import java.util.stream.Stream;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Utility to extract all Java CodeUnits from a directory and save them to a CSV.
 */
public class CodeUnitExtractor {
    private static final Logger logger = LogManager.getLogger(CodeUnitExtractor.class);

    public static void main(String[] args) {
        // Determine paths relative to project structure
        Path cwd = Path.of("").toAbsolutePath();
        
        // Find the app source directory - try both from project root and from app directory
        Path appSrcPath;
        if (args.length > 0) {
            appSrcPath = Path.of(args[0]).toAbsolutePath().normalize();
        } else if (Files.isDirectory(cwd.resolve("app/src/main/java"))) {
            appSrcPath = cwd.resolve("app/src/main/java");
        } else if (Files.isDirectory(cwd.resolve("src/main/java"))) {
            appSrcPath = cwd.resolve("src/main/java");
        } else {
            throw new IllegalStateException("Cannot find source directory. Run from project root or specify path as argument.");
        }
        
        // Find the output directory - try both from project root and from app directory
        Path outputPath;
        if (args.length > 1) {
            outputPath = Path.of(args[1]).toAbsolutePath().normalize();
        } else if (Files.isDirectory(cwd.resolve("app/src/test/resources")) || Files.isDirectory(cwd.resolve("app/src/test"))) {
            outputPath = cwd.resolve("app/src/test/resources/codeunits.csv");
        } else if (Files.isDirectory(cwd.resolve("src/test/resources")) || Files.isDirectory(cwd.resolve("src/test"))) {
            outputPath = cwd.resolve("src/test/resources/codeunits.csv");
        } else {
            throw new IllegalStateException("Cannot find test resources directory. Run from project root or specify path as argument.");
        }
        
        Path projectRoot = appSrcPath;

        try {
            extract(projectRoot, outputPath);
            logger.info("Extraction complete.");
        } catch (Exception e) {
            logger.error("Failed to extract CodeUnits: {}", e.getMessage(), e);
            System.exit(1);
        }
    }

    /**
     * Loads CodeUnits from a CSV stream generated by this tool.
     * Reconstructs the objects using dummy ProjectFile paths relative to the provided project root.
     */
    public static List<CodeUnit> loadCodeUnits(InputStream csvStream, IProject project) throws IOException {
        List<CodeUnit> units = new ArrayList<>();
        Path root = project.getRoot();

        try (BufferedReader reader = new BufferedReader(new InputStreamReader(csvStream, StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.isBlank()) continue;
                String[] parts = line.split(",", -1);
                if (parts.length >= 4) {
                    try {
                        CodeUnitType kind = CodeUnitType.valueOf(parts[0]);
                        String fqName = parts[1];
                        String shortName = parts[2];

                        // Determine package name from FQN and shortName
                        String packageName = "";
                        if (fqName.length() > shortName.length()) {
                            packageName = fqName.substring(0, fqName.length() - shortName.length() - 1);
                        }

                        // Create a dummy ProjectFile. Since we don't store the original path in the 4-column CSV,
                        // we use a path derived from the package name as a placeholder.
                        String dummyRelPath = packageName.replace('.', '/') + "/" + shortName + ".java";
                        ProjectFile source = new ProjectFile(root, dummyRelPath);

                        units.add(new CodeUnit(source, kind, packageName, shortName));
                    } catch (IllegalArgumentException ignored) {
                        // Skip lines with unknown types or malformed data
                    }
                }
            }
        }
        return units;
    }

    public static void extract(Path projectRoot, Path outputPath) throws IOException {
        logger.info("Extracting CodeUnits from: {}", projectRoot);

        if (!Files.isDirectory(projectRoot)) {
            throw new IllegalArgumentException("Provided path is not a directory: " + projectRoot);
        }

        IProject project = createMinimalProject(projectRoot);
        JavaAnalyzer analyzer = new JavaAnalyzer(project);

        logger.info("Analyzing files...");
        analyzer.update();

        List<CodeUnit> declarations = analyzer.getAllDeclarations();
        logger.info("Found {} declarations. Writing to {}...", declarations.size(), outputPath);

        List<String> lines = declarations.stream()
                .map(cu -> String.format("%s,%s,%s,%s", cu.kind(), cu.fqName(), cu.shortName(), cu.identifier()))
                .sorted()
                .toList();

        Path parent = outputPath.getParent();
        if (parent != null) {
            Files.createDirectories(parent);
        }
        Files.write(outputPath, lines);
    }

    private static IProject createMinimalProject(Path root) {
        return new IProject() {
            @Override
            public Path getRoot() {
                return root;
            }

            @Override
            public Set<ProjectFile> getAllFiles() {
                try (Stream<Path> stream = Files.walk(root)) {
                    List<Path> paths = stream.filter(Files::isRegularFile)
                            .filter(p -> p.toString().endsWith(".java"))
                            .toList();
                    logger.info("Found {} java files under {}", paths.size(), root);
                    return paths.stream()
                            .map(p -> new ProjectFile(root, root.relativize(p)))
                            .collect(Collectors.toSet());
                } catch (IOException e) {
                    throw new RuntimeException("Failed to list files in " + root, e);
                }
            }

            @Override
            public void close() {
                // No-op for this tool
            }
        };
    }
}
