name: CI

on:
  push:
    branches: [ 'master', 'ci/**' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: npm
        cache-dependency-path: frontend-mop/package-lock.json

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Install frontend dependencies
      run: npm ci
      working-directory: frontend-mop

    - name: Check commit
      run: git rev-parse HEAD

    - name: Run tests
      run: ./gradlew test

    - name: Build assembly
      run: ./gradlew shadowJar


  formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Check code formatting
        run: ./gradlew spotlessCheck

  dependency-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend-mop/package-lock.json

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend-mop

      - name: Run dependency analysis
        run: ./gradlew buildHealth
