name: Sync Master to Snapshot

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to master-snapshot
        run: |
          git push origin master:master-snapshot --force
